# the remote data service
cc_library(
    name = "svc",
    srcs = [
        "svc.cc",
        "svc.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//net/api",
        "//net/api:codec",
        "@lager",
        "@scelta",
        "@zug",
    ],
)
