cc_library(
    name = "client",
    srcs = [
        "client.cc",
        "client.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//foo",
        "//net/api",
        "@lager",
        "@scelta",
        "@zug",
    ],
)
