cc_library(
    name = "ws",
    srcs = [
        "ws.cc",
        "ws.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//net/api:codec",
        "@lager",
        "@scelta",
        "@zug",
    ],
)
