cc_library(
    name = "foo",
    srcs = [
        "foo.cc",
        "foo.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bar",
        "//common",
        "//net:api",
        "@lager",
        "@scelta",
        "@zug",
    ],
)
