cc_library(
    name = "baz",
    srcs = [
        "baz.cc",
        "baz.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//common",
        "@lager",
        "@scelta",
        "@zug",
    ],
)
