cc_library(
    name = "bar",
    srcs = [
        "bar.cc",
        "bar.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//common",
        "@lager",
        "@scelta",
        "@zug",
    ],
)
